#repos:
#-   repo: local
#    hooks:
#    - id: nbdev_clean # hook id 
#      name: nbdev clean # some readable name
#      entry: ./.pre-commit-hooks/run_nbdev_on_staged_files.bat # path to the script
#      language: system # how to run the script
#      types: [jupyter] # what to run it on
#      stages: [commit] # when to run it